### ISSUE TITLE
Built for 20.04 (focal)

### ISSUE THREAD

**Issue by buchnerh** [mzanetti/kodimote#101]
Can you please built kodimote for the upcoming Ubuntu Touch 20.04 (focal)?
Thanks!

**Comment by luksus42** [comment]
Focal build is now in OpenStore.
Code is here: https://github.com/luksus42/kodimote/tree/ut-focal

I also switched the support urls in OpenStore to my fork.

**Comment by mzanetti** [comment]
thanks!
