### ISSUE TITLE
Investigate adding support for addons

### ISSUE THREAD

**Issue by RobertMe** [mzanetti/kodimote#12]
At least in Jolla Harbour there are multiple comments about supporting addons. But as far as I know currently apps are only able to retrieve a list of installed addons, and execute one. But I don't think it's possible to, for example, browse YouTube using the addon (except simply using the keypad). 1. because Kodi doesn't have some generic API interface for this (browsing video addons in this case), and 2. addons can't extend the JSON interface on their own.

In some cases it might be possible to play some special URLs to trigger an addon to run (I think I've seen something like `youtube://location of video` to play a YouTube video) but this would require some interface to trigger these (addon for the webbrowser/share framework? cooperation with native youtube app?)

So in this issue report I'd like to collect user feedback on what users would like us to support, and discuss ways on how to add support for these (what is possible using the current Kodi API? What UX is needed/possible? ...).

**Comment by RobertMe** [comment]
So, to kick off.
What is supported by the API, and can be easily implemented is adding a (main) menu item to list all addons, and opening/executing it by clicking on it (in case the addon supports execution).

Although not supported by the API these addons could be grouped by their type, although it does require us to add a list with translations for all/the most common addon types.

**Comment by RobertMe** [comment]
I've just found this thread: http://forum.kodi.tv/showthread.php?tid=207677 and done some testing (using the YouTube addon).

Usage seems to be pretty simple:
**List main items of (YT) addon**
```
curl -i -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"Files.GetDirectory","params":{"directory": "plugin://plugin.video.youtube" },"id":1}' http://localhost:9191/jsonrpc
```
This returns the directories content, build as new directories:
```JSON
{
   "id":1,
   "jsonrpc":"2.0",
   "result":{
      "files":[
         {
            "file":"plugin://plugin.video.youtube/sign/in/",
            "filetype":"directory",
            "label":"[B]Sign In[/B]",
            "type":"unknown"
         },
         {
            "file":"plugin://plugin.video.youtube/special/what_to_watch/",
            "filetype":"directory",
            "label":"[B]What to watch[/B]",
            "type":"unknown"
         },
         {
            "file":"plugin://plugin.video.youtube/kodion/search/list/",
            "filetype":"directory",
            "label":"Search",
            "type":"unknown"
         },
         {
            "file":"plugin://plugin.video.youtube/special/browse_channels/",
            "filetype":"directory",
            "label":"Browse Channels",
            "type":"unknown"
         }
      ],
      "limits":{
         "end":4,
         "start":0,
         "total":4
      }
   }
}
```
And these directories can then be opened, again using `Files.GetDirectory`.

**List previous searches**
```
curl -i -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"Files.GetDirectory","params":{"directory": "plugin://plugin.video.youtube/kodion/search/list/" },"id":1}' http://localhost:9191/jsonrpc
```

Which for example returns:
```JSON
{
   "id":1,
   "jsonrpc":"2.0",
   "result":{
      "files":[
         {
            "file":"plugin://plugin.video.youtube/kodion/search/new/",
            "filetype":"directory",
            "label":"[B]New Search[/B]",
            "type":"unknown"
         },
         {
            "file":"plugin://plugin.video.youtube/kodion/search/query/?q=test",
            "filetype":"directory",
            "label":"test",
            "type":"unknown"
         }
      ],
      "limits":{
         "end":2,
         "start":0,
         "total":2
      }
   }
}
```

This result could then be used to open a new directory once again. In the case of the `search/new` URL this will show the search dialog in Kodi. But, as we support input dialogs, you can also enter the search text on the phone itself. When the text is entered the dialog will close again, and the search results will be send back as a new directory listing. This will contain some files and some directories. So for directories you can once again open the directory, and for files, we can add the file URL to the current playlist.

So when we have an addon listing, we can enter those with a `xbmc.python.pluginsource` type by opening the `Files` model with the dir set to `plugin://<addonid>`

**Comment by mzanetti** [comment]
merged
