### ISSUE TITLE
Remember "show watched" setting

### ISSUE THREAD

**Issue by RobertMe** [mzanetti/kodimote#17]
The "show watched" flag is currently only used for the current page/view. This should at least be used for all the sub pages of the current page/view where the flag is set. Preferably it's even a setting which is automatically saved from the model (possibly two (or more?) settings, one for music, one for video, just like Kodi has).

**Comment by mzanetti** [comment]
I don't think the setting should affect other folders than the current one. However, I agree that it should be saved.

**Comment by RobertMe** [comment]
Just checked how Kodi does it. There are probably only two underlying settings, one for movies, and one for TV Shows (+ one for music videos?), the music library doesn't seem to support this. So when you set it in TV Shows it also works for the seasons and episodes, but not for movies. Having it affect the "sub folders" would thus only be the case for TV Shows. And that's also the area where it's annoying that it isn't remembered.

When I want to find the first unwatched episode of a show quickly I'll just mark "hide watched" for the TV Shows, so I can find the show easily, and I then want to click the first items on screen (season => episode), as those are still filtered on the watched state.

I don't mind having to reset the filter every time I open TV Shows, but I do mind if I have to re-set it for every sub folder. And having a setting for every view would also be really confusing (show watched TV Shows, but hide its watched seasons, but then again do show its watched episodes).
