### ISSUE TITLE
cannot authenticate

### ISSUE THREAD

**Issue by accumulator** [mzanetti/kodimote#31]
If there is an existing host in kodimote, but it has no credentials entered yet, kodimote tries to connect, then shows the authentication dialog. Every few seconds it pops up a new authentication dialog, so it's impossible to fill in the credentials

**Comment by accumulator** [comment]
@RobertMe I think this is related to the reconnection changes

**Comment by RobertMe** [comment]
Reproduced, will make a patch for it.

I think it's because the reconnect timer keeps running when authentication fails, shouldn't be hard to fix.

@mzanetti can you also reproduce on Ubuntu?
