### ISSUE TITLE
[feature request]Show "watched" tags in "Files" lists.

### ISSUE THREAD

**Issue by rawler** [mzanetti/kodimote#79]
When looking through, for example TV shows, a "watched" marking would make it a lot easier to find the right episode.

**Comment by mzanetti** [comment]
That's already there...

**Comment by mzanetti** [comment]
If it doesn't work for you, feel free to re-open but please give more details. What platform, what version are you using?

**Comment by RobertMe** [comment]
Just tested on Sailfish and working fine there (too). Although the colors are based on the ambience, so it might be possible that for some ambiences the marker doesn't stand out that much.

So some info about the platform (and version) and Kodimote version would indeed be helpful.

**Comment by rawler** [comment]
Using Kodimote (2.1.2.2) on Meizu MX4 Ubuntu (15.04r3), upgraded to latest versions. Using with latest version of OpenELEC (not able to check ATM)

**Comment by mzanetti** [comment]
@rawler Here's a screenshot on my Meizu MX4: http://i.imgur.com/7iIzKl8.png

See the ticks on the lower right corner of each list entry? That's the watched flag.

**Comment by rawler** [comment]
Nope, I'm pretty sure I would have seen them if they were shown for me.
Could it be due to me using "files", not TV-series? Kodi still tracks
"shown" for files...

2015-08-25 16:08 GMT+02:00 mzanetti <notifications@github.com>:

**Comment by mzanetti** [comment]
That's most likely it, yes. Need to check if the API allows us to get this kind of information for "files".

**Comment by RobertMe** [comment]
Created #80 to fix this issue. Tested with Kodi 14 (and might also work for older/XMBC versions).
