### ISSUE TITLE
Make it clear that kodimote uses port 9090

### ISSUE THREAD

**Issue by ethercrow** [mzanetti/kodimote#81]
I had port 9090 firewalled on my kodi box and ios kodi remote worked fine, while jolla kodimote couldn't connect to it.

How about telling the user to make sure that port 9090 is open in the same dialog that tells them to configure kodi access from other devices?

**Comment by mzanetti** [comment]
I don't think this is necessary to go beyond mentioning the UI options one has to enable in kodi. When a user manually sets up a firewall he should be able to figure those details. It will only confuse non technical users.
