### ISSUE TITLE
Conflict between UT keyboard word suggestions/spell checking and Kodimote authentication form

### ISSUE THREAD

**Issue by ilgiaco** [mzanetti/kodimote#82]
Hi,
I noticed that if I try to fill the authentication fields with word suggestions or spell checking enabled in Ubuntu Touch keyboard settings, when pressing ok for confirmation the login doesn't succeed, the fields are cleared and I'm prompted for login credentials once again.
In order to make it work correctly I need to deselect the last word in the password field before confirming. 
I think the form doesn't manage correctly the last typed word, but only when that keyboard settings are enabled.

**Comment by mzanetti** [comment]
This has been fixed with 2.1.2.3
