### ISSUE TITLE
Credentials are not accepted

### ISSUE THREAD

**Issue by ernesst** [mzanetti/kodimote#83]
Currently, the app detect my kodi server, however i cannot go further than the credential prompt. 
Even with correct login and password the prompt comes back.
I don't have this issue with the xbmcmote app. 

please find the connection log : 
I'm not sure about the argument error line 2... 
command : "/opt/click.ubuntu.com/com.ubuntu.developer.mzanetti.kodimote/current/kodimote -d connection --  --desktop_file_hint=/home/phablet/.local/share/applications/com.ubuntu.developer.mzanetti.kodimote_kodimote_2.1.2.2.desktop > foo.log 2>&1"

Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
/opt/click.ubuntu.com/com.ubuntu.developer.mzanetti.kodimote/current/kodimote: invalid option -- 'd'
got language: "en-GB"
"couldn't load qt_en-GB"
Cannot load translation file "kodimote_en-GB.pm"
args are ("/opt/click.ubuntu.com/com.ubuntu.developer.mzanetti.kodimote/current/kodimote", "-d", "connection", "--", "--desktop_file_hint=/home/phablet/.local/share/applications/com.ubuntu.developer.mzanetti.kodimote_kodimote_2.1.2.2.desktop")
rating -1
player created libraryItem LibraryItem(0x1c86af8) -1
rating -1
player created libraryItem LibraryItem(0x1c90b70) -1
rating -1
player created libraryItem LibraryItem(0x1c90f80) -1
APP_ID isn't set, the handler can not be registered
current socket state QAbstractSocket::UnconnectedState
current socket state QAbstractSocket::UnconnectedState
APP_ID isn't set, the handler ignored
No host given and no previously connected host stored. Cannot connect.
found host
added host QUuid("{a4881c3b-d93e-4d72-9de4-1ae586537d39}")
host inserted
UbuntuWindow::handleSurfaceFocusChange(focused=true)
UbuntuWindow::handleSurfaceFocusChange(focused=false)
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... false
current socket state QAbstractSocket::UnconnectedState
current socket state QAbstractSocket::UnconnectedState
found host
UbuntuWindow::handleSurfaceFocusChange(focused=true)
APP_ID isn't set, the handler ignored
found host
connecting host KodiHostModel(0x1c861b0)
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
Start connecting to host
connecting to "Kodi (tiziano)" "192.168.0.115" "" (using password: false )
current socket state QAbstractSocket::ConnectingState
qml: connecting..... true
current socket state QAbstractSocket::ConnectingState
Connected to remote host. Asking for version...
sending command to  QUrl( "http://192.168.0.115:8080/jsonrpc" )  : "{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "JSONRPC.Version"
}
"
Authentication required
qml: auth required
qrc:///qml/main.qml:577:13: QML Flickable: Binding loop detected for property "height"
No connection yet, cannot disconnect.
Disconnected
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
timeouttimer hit for command 0 "JSONRPC.Version"
cannot ask for remote version... 
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
cannot send... busy
setting auth credentials
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
Start connecting to host
connecting to "Kodi (tiziano)" "192.168.0.115" "kodi" (using password: false )
current socket state QAbstractSocket::ConnectingState
qml: connecting..... true
current socket state QAbstractSocket::ConnectingState
Connected to remote host. Asking for version...
sending command to  QUrl( "http://192.168.0.115:8080/jsonrpc" )  : "{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "JSONRPC.Version"
}
"
Authentication required
qml: auth required
qrc:///qml/main.qml:577:13: QML Flickable: Binding loop detected for property "height"
No connection yet, cannot disconnect.
Disconnected
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
UbuntuWindow::handleSurfaceFocusChange(focused=false)
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
UbuntuWindow::handleSurfaceFocusChange(focused=true)
APP_ID isn't set, the handler ignored
current socket state QAbstractSocket::UnconnectedState
qml: connecting..... true
current socket state QAbstractSocket::UnconnectedState
Start connecting to host
connecting to "Kodi (tiziano)" "192.168.0.115" "kodi" (using password: false )
current socket state QAbstractSocket::ConnectingState
qml: connecting..... true
current socket state QAbstractSocket::ConnectingState
Connected to remote host. Asking for version...
cannot send... busy
UbuntuWindow::handleSurfaceFocusChange(focused=false)

**Comment by mzanetti** [comment]
please the the latest update. I hope it fixes this issue
