### ISSUE TITLE
Cannot seem to build for Harmattan

### ISSUE THREAD

**Issue by cockroach** [mzanetti/kodimote#85]
It seems the current version fails to compile for Harmattan.

libkodimote aborts saying `libkodimote/../../kodimote/libkodimote/mpris2/mpriscontroller.h:26: error: QWindow: No such file or directory`, the Harmattan "app" consequently also fails to compile.

Revision 1fde6a7867f306d011aab3c10fc13477bfe15792 compiles just fine btw and still seems to work with recent versions of Kodi, it's a bit old though and I assume at some point compatibility is going to break -- having an up-to-date version of kodimote available at that point would be fantastic.

**Comment by mzanetti** [comment]
Sorry, the N9 is not officially maintained any more.

If someone wants to pick it up, please feel free to reopen this ticket and start working on it.
