### ISSUE TITLE
Wrong action for shutdown

### ISSUE THREAD

**Issue by buchnerh** [mzanetti/kodimote#98]
I've connected my Kodi Host (Version 17 on Debian Buster) with my BQ E4.5. Everything works fine except the shutdown. When I press "Shutdown Kodi Host" in kodimote I expect that the whole computer will be shut down but instead only kodi is closed. The option "Restart Kodi Host" for example does exactly what it offers, restarting the computer.
I've activated the debug-log in kodi and found these lines when I press "Shutdown Kodi Host":

`NOTICE: Storing total System Uptime
DEBUG: CAnnouncementManager - Announcement: OnQuit from xbmc
NOTICE: Saving settings
DEBUG: GOT ANNOUNCEMENT, type: 8, from xbmc, message OnQuit`

As you can see, the AnnouncementManager receives a Quit-Announcement and not a Shutdown-Announcement. So I think, that the wrong event is triggered within kodimote.

**Comment by buchnerh** [comment]
I think I've found the problem:
In PowerMenu.qml row 50 the command should be "kodi.shutdown" instead of "kodi.quit".
I think it's a simple copy & paste error. Could you please correct the error and upload the new version?

Thanks!

**Comment by mzanetti** [comment]
Hi,
on which platform are you using it?

I'm not actively maintaining this any more, but if you'd file a pull request I can probably ping the according people to upload a new build.

**Comment by buchnerh** [comment]
Hi,

I'm using it on my BQ E4.5 with Ubuntu Touch 16.04 / UBports OTA 16.
I've filled a pull request for this change, thanks for merging it!

**Comment by mzanetti** [comment]
Merged. I've asked the package maintainer to update the package in the open store.

**Comment by mzanetti** [comment]
On a similar note, you could also install nymea on your kodi machine an then use nymea:app to control kodi. It should support mostly the same feature as kodimote (even look similar) and additionally allows you to automatically dim your living room lights when you watch movies and similar things.

it's also available on the open store.

**Comment by mzanetti** [comment]
Package has been updated on the open store.
